swagger: "2.0"
info:
  version: 0.0.1
  title: title
  description: description
  termsOfService: terms
  contact:
    name: Zoltan
    email: zgiber@gmail.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
paths:
  /login:
    get:
      summary: hello
      description: nothing
      responses:
        200:
          description: OK
    